name: artisanal_workspace
publish_to: none
workspace:
  - pkgs/artisanal
  - pkgs/artisanal_widgets
  - pkgs/artisanal_widgets/example/github_cli
  - pkgs/artisanal_widgets/example/flutter_cli_port
  - pkgs/ultraviolet
  - pkgs/flutter_artisanal

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.10.0 <4.0.0"
