name: artisanal_workspace
publish_to: none
workspace:
  - apps/artisanal_editor
  - apps/github_cli
  - apps/opencode
  - pkgs/artisanal
  - pkgs/artisanal/example/tree_sitter_language_pack
  - pkgs/artisanal_pty
  - pkgs/artisanal_widgets
  - pkgs/artisanal_widgets/example/flutter_cli_port
  - pkgs/ultraviolet
  - pkgs/flutter_artisanal

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.10.0 <4.0.0"
