name: artisanal_workspace
publish_to: none
workspace:
  - pkgs/artisanal
  - pkgs/artisanal_widgets
  - pkgs/dash_ai
  - pkgs/dash_agent
  - pkgs/dash
  - pkgs/dash_acp
  - pkgs/dash_cli
  - pkgs/dash_lsp
  - pkgs/dash_mcp
  - pkgs/dash_memory
  - pkgs/dash_ui
  - pkgs/dash_web
  - pkgs/dash_tui
  - pkgs/dash_pty
  - pkgs/ultraviolet

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.10.0 <4.0.0"
