const _intercepted = ['run', 'test', 'build', 'devices'];

String renderInitShim(String shell) {
  return switch (shell) {
    'zsh' || 'bash' => _renderPosix(shell),
    'fish' => _renderFish(),
    _ => 'unsupported shell: $shell\n',
  };
}

String _renderPosix(String shell) {
  final cases = _intercepted
      .map((cmd) => '    $cmd) shift; command flutter-cli $cmd "\$@" ;;')
      .join('\n');
  return '''
# flutter-cli shim — generated by `flutter-cli init`. Drop in
# your rc file via:
#   eval "\$(flutter-cli init $shell)"
# Place this AFTER any other tool that defines `flutter`.
unalias flutter 2>/dev/null
flutter() {
  if ! command -v flutter-cli >/dev/null 2>&1; then
    command flutter "\$@"
    return
  fi
  case "\$1" in
$cases
    *) command flutter "\$@" ;;
  esac
}
''';
}

String _renderFish() {
  final cases = _intercepted
      .map(
        (cmd) => '    case $cmd\n        command flutter-cli $cmd \$argv[2..]',
      )
      .join('\n');
  return '''
# flutter-cli shim — generated by `flutter-cli init fish`.
# Drop this in ~/.config/fish/config.fish via:
#   flutter-cli init fish | source
function flutter
    if not command -q flutter-cli
        command flutter \$argv
        return
    end
    switch \$argv[1]
$cases
    case '*'
        command flutter \$argv
    end
end
''';
}
