Output pkgs/artisanal/assets/lipgloss_tui.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1200
Set Height 700
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/artisanal/lipgloss_tui.dill list"
Enter
Wait+Screen /lunch/
Sleep 1s
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Type "j"
Sleep 300ms
Type "G"
Sleep 400ms
Type "g"
Sleep 400ms
Type "j"
Sleep 300ms
Type "j"
Sleep 400ms
Enter
Sleep 2s
