Output pkgs/artisanal/assets/multi_search_demo.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1000
Set Height 600
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/artisanal/multi_search_demo.dill"
Enter
Wait+Screen /Select your favorite fruits/
Sleep 2s
Type "ap"
Sleep 1s
Type " "
Sleep 600ms
Enter
Sleep 1.5s
