name: github_cli
description: GitHub terminal dashboard example for artisanal_widgets.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

executables:
  github_cli:

dependencies:
  args: ^2.6.0
  artisanal: ^0.3.1-wip
  artisanal_widgets: ^0.2.1-wip
  devtools_region_profiler: ^0.1.0
  http: ^1.2.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.4.12
  image: ^4.7.1
  lints: ^6.0.0
  test: ^1.28.0
