import 'dart:convert';

import 'package:artisanal/style.dart';
import 'package:characters/characters.dart';

final class _Cell {
  _Cell();
  String text = ' ';
  String sgr = '';
}

final class _SavedScreen {
  _SavedScreen({
    required this.rows,
    required this.cursorX,
    required this.cursorY,
    required this.sgr,
    required this.cursorVisible,
    required this.scrollOffset,
    required this.keyboardEnhancementFlags,
    required this.keyboardFlagStack,
  });

  List<List<_Cell>> rows;
  int cursorX;
  int cursorY;
  String sgr;
  bool cursorVisible;
  int scrollOffset;
  int keyboardEnhancementFlags;
  List<int> keyboardFlagStack;
}

/// Mouse event reporting requested by the hosted terminal application.
enum TerminalMouseTracking { none, button, drag, all }

const _supportedKeyboardEnhancements = 1 | 2 | 8;

/// A small, transport-independent ANSI/VT screen model.
///
/// Feed bytes from a local PTY, SSH connection, or fixture to [write]. The
/// model intentionally owns no process so it remains deterministic in tests.
final class VirtualTerminal {
  /// Creates a terminal with [width] columns and [height] rows.
  VirtualTerminal({
    this.width = 80,
    this.height = 24,
    this.scrollbackLimit = 10000,
  }) : assert(width > 0),
       assert(height > 0),
       assert(scrollbackLimit >= 0),
       _rows = List.generate(
         height,
         (_) => List.generate(width, (_) => _Cell()),
       );

  int width;
  int height;
  final int scrollbackLimit;
  List<List<_Cell>> _rows;
  final List<List<_Cell>> _scrollback = [];
  int cursorX = 0;
  int cursorY = 0;
  int scrollOffset = 0;
  String _sgr = '';
  String _pending = '';
  final List<int> _pendingBytes = [];
  final StringBuffer _pendingResponses = StringBuffer();
  final List<int> _keyboardFlagStack = [];
  final List<void Function()> _listeners = [];
  _SavedScreen? _primaryScreen;
  bool _mouseButtonTracking = false;
  bool _mouseDragTracking = false;
  bool _mouseAllTracking = false;

  /// Whether the emulated cursor is visible.
  bool cursorVisible = true;

  /// Whether cursor keys should use DEC application-mode sequences.
  bool applicationCursorKeys = false;

  /// Kitty keyboard-protocol enhancement flags requested by the application.
  int keyboardEnhancementFlags = 0;

  /// Whether the alternate screen buffer is active.
  bool alternateScreen = false;

  /// Whether SGR extended mouse coordinates are enabled.
  bool sgrMouseCoordinates = false;

  /// Whether urxvt extended mouse coordinates are enabled.
  bool urxvtMouseCoordinates = false;

  /// The strongest mouse tracking mode currently requested.
  TerminalMouseTracking get mouseTracking {
    if (_mouseAllTracking) return TerminalMouseTracking.all;
    if (_mouseDragTracking) return TerminalMouseTracking.drag;
    if (_mouseButtonTracking) return TerminalMouseTracking.button;
    return TerminalMouseTracking.none;
  }

  /// Number of retained rows above the visible primary screen.
  int get scrollbackLength => alternateScreen ? 0 : _scrollback.length;

  /// Scrolls the primary-screen viewport by [delta] rows.
  ///
  /// Positive values move backward into older output.
  bool scrollBy(int delta) {
    if (alternateScreen || delta == 0) return false;
    final next = (scrollOffset + delta).clamp(0, _scrollback.length);
    if (next == scrollOffset) return false;
    scrollOffset = next;
    _notify();
    return true;
  }

  /// Returns the primary-screen viewport to the newest output.
  bool scrollToBottom() {
    if (scrollOffset == 0) return false;
    scrollOffset = 0;
    _notify();
    return true;
  }

  /// Returns and clears terminal protocol responses generated by output.
  ///
  /// Hosts should write this value back to their PTY or remote transport.
  String takePendingResponses() {
    final value = _pendingResponses.toString();
    _pendingResponses.clear();
    return value;
  }

  /// Adds a callback invoked after writes and resizes.
  void addListener(void Function() listener) => _listeners.add(listener);

  /// Removes a callback.
  void removeListener(void Function() listener) => _listeners.remove(listener);

  /// Releases listeners held by this model.
  void dispose() => _listeners.clear();

  /// Changes the screen dimensions while retaining the top-left contents.
  void resize(int newWidth, int newHeight) {
    if (newWidth <= 0 || newHeight <= 0) {
      throw ArgumentError('Terminal dimensions must be positive.');
    }
    if (newWidth == width && newHeight == height) return;
    final next = _resizeRows(_rows, newWidth, newHeight);
    final primary = _primaryScreen;
    if (primary != null) {
      primary.rows = _resizeRows(primary.rows, newWidth, newHeight);
      primary.cursorX = primary.cursorX.clamp(0, newWidth - 1);
      primary.cursorY = primary.cursorY.clamp(0, newHeight - 1);
    }
    for (var index = 0; index < _scrollback.length; index++) {
      _scrollback[index] = _resizeRows(
        [_scrollback[index]],
        newWidth,
        1,
      ).single;
    }
    width = newWidth;
    height = newHeight;
    _rows = next;
    cursorX = cursorX.clamp(0, width - 1);
    cursorY = cursorY.clamp(0, height - 1);
    _notify();
  }

  List<List<_Cell>> _resizeRows(
    List<List<_Cell>> source,
    int newWidth,
    int newHeight,
  ) {
    final oldHeight = source.length;
    final oldWidth = source.firstOrNull?.length ?? 0;
    return List.generate(
      newHeight,
      (y) => List.generate(
        newWidth,
        (x) => y < oldHeight && x < oldWidth ? source[y][x] : _Cell(),
      ),
    );
  }

  /// Processes a chunk of UTF-8 terminal output.
  void write(List<int> bytes) {
    _pendingBytes.addAll(bytes);
    for (
      var suffix = 0;
      suffix <= 3 && suffix <= _pendingBytes.length;
      suffix++
    ) {
      final completeLength = _pendingBytes.length - suffix;
      try {
        final text = utf8.decode(
          _pendingBytes.sublist(0, completeLength),
          allowMalformed: false,
        );
        _pendingBytes.removeRange(0, completeLength);
        if (text.isNotEmpty) writeText(text);
        return;
      } on FormatException {
        // A trailing UTF-8 sequence may be completed by the next chunk.
      }
    }
    if (_pendingBytes.length > 4) {
      final text = utf8.decode(_pendingBytes, allowMalformed: true);
      _pendingBytes.clear();
      writeText(text);
    }
  }

  /// Processes terminal output already decoded as text.
  void writeText(String value) {
    final input = '$_pending$value';
    _pending = '';
    for (var i = 0; i < input.length;) {
      if (input.codeUnitAt(i) == 0x1b) {
        if (i + 1 >= input.length) {
          _pending = input.substring(i);
          break;
        }
        if (input[i + 1] == '[') {
          final end = _csiEnd(input, i + 2);
          if (end < 0) {
            _pending = input.substring(i);
            break;
          }
          _handleCsi(input.substring(i + 2, end), input[end]);
          i = end + 1;
          continue;
        }
        if (input[i + 1] == ']') {
          final end = _oscEnd(input, i + 2);
          if (end < 0) {
            _pending = input.substring(i);
            break;
          }
          i = input.codeUnitAt(end) == 0x07 ? end + 1 : end + 2;
          continue;
        }
        i += 2;
        continue;
      }
      final codeUnit = input.codeUnitAt(i);
      if (codeUnit == 8 || codeUnit == 9 || codeUnit == 10 || codeUnit == 13) {
        _print(String.fromCharCode(codeUnit));
        i++;
        continue;
      }
      final character = input.substring(i).characters.first;
      _print(character);
      i += character.length;
    }
    _notify();
  }

  int _csiEnd(String input, int start) {
    for (var i = start; i < input.length; i++) {
      final c = input.codeUnitAt(i);
      if (c >= 0x40 && c <= 0x7e) return i;
    }
    return -1;
  }

  int _oscEnd(String input, int start) {
    for (var i = start; i < input.length; i++) {
      if (input.codeUnitAt(i) == 0x07) return i;
      if (input.codeUnitAt(i) == 0x1b &&
          i + 1 < input.length &&
          input[i + 1] == r'\') {
        return i;
      }
    }
    return -1;
  }

  void _print(String character) {
    switch (character) {
      case '\r':
        cursorX = 0;
        return;
      case '\n':
        _lineFeed();
        return;
      case '\b':
        cursorX = (cursorX - 1).clamp(0, width - 1);
        return;
      case '\t':
        cursorX = ((cursorX ~/ 8 + 1) * 8).clamp(0, width - 1);
        return;
    }
    if (cursorX >= width) {
      cursorX = 0;
      _lineFeed();
    }
    final displayWidth = Layout.getWidth(character).clamp(1, 2);
    if (displayWidth == 2 && cursorX == width - 1) {
      cursorX = 0;
      _lineFeed();
    }
    _rows[cursorY][cursorX]
      ..text = character
      ..sgr = _sgr;
    if (displayWidth == 2) {
      _rows[cursorY][cursorX + 1]
        ..text = ''
        ..sgr = _sgr;
    }
    cursorX += displayWidth;
  }

  void _lineFeed() {
    cursorY++;
    if (cursorY < height) return;
    final removed = _rows.removeAt(0);
    if (!alternateScreen && scrollbackLimit > 0) {
      if (scrollOffset > 0) scrollOffset++;
      _scrollback.add(removed);
      if (_scrollback.length > scrollbackLimit) {
        _scrollback.removeRange(0, _scrollback.length - scrollbackLimit);
      }
      scrollOffset = scrollOffset.clamp(0, _scrollback.length);
    }
    _rows.add(List.generate(width, (_) => _Cell()));
    cursorY = height - 1;
  }

  void _handleCsi(String body, String command) {
    if (command == 'u') {
      if (body.startsWith('>')) {
        final params = _keyboardParams(body.substring(1));
        if (_keyboardFlagStack.length == 64) {
          _keyboardFlagStack.removeAt(0);
        }
        _keyboardFlagStack.add(keyboardEnhancementFlags);
        _applyKeyboardFlags(
          params.firstOrNull ?? 0,
          params.length > 1 ? params[1] : 1,
        );
        return;
      }
      if (body.startsWith('=')) {
        final params = _keyboardParams(body.substring(1));
        _applyKeyboardFlags(
          params.firstOrNull ?? 0,
          params.length > 1 ? params[1] : 1,
        );
        return;
      }
      if (body.startsWith('<')) {
        final params = _keyboardParams(body.substring(1));
        final count = params.firstOrNull ?? 1;
        for (var index = 0; index < count; index++) {
          keyboardEnhancementFlags = _keyboardFlagStack.isEmpty
              ? 0
              : _keyboardFlagStack.removeLast();
        }
        return;
      }
      if (body == '?') {
        _pendingResponses.write(
          '\x1b[?$keyboardEnhancementFlags'
          'u',
        );
        return;
      }
    }

    final private = body.startsWith('?');
    final raw = private ? body.substring(1) : body;
    final params = raw.isEmpty
        ? <int>[]
        : raw.split(';').map((v) => int.tryParse(v) ?? 0).toList();
    int param(int index, [int fallback = 1]) =>
        index < params.length && params[index] != 0 ? params[index] : fallback;
    if (private) {
      final enabled = command == 'h';
      for (final value in params) {
        switch (value) {
          case 1:
            applicationCursorKeys = enabled;
          case 25:
            cursorVisible = enabled;
          case 47 || 1047 || 1049:
            _setAlternateScreen(enabled);
          case 1000:
            _mouseButtonTracking = enabled;
          case 1002:
            _mouseDragTracking = enabled;
          case 1003:
            _mouseAllTracking = enabled;
          case 1006:
            sgrMouseCoordinates = enabled;
          case 1015:
            urxvtMouseCoordinates = enabled;
        }
      }
      return;
    }
    switch (command) {
      case 'A':
        cursorY = (cursorY - param(0)).clamp(0, height - 1);
      case 'B':
        cursorY = (cursorY + param(0)).clamp(0, height - 1);
      case 'C':
        cursorX = (cursorX + param(0)).clamp(0, width - 1);
      case 'D':
        cursorX = (cursorX - param(0)).clamp(0, width - 1);
      case 'H':
      case 'f':
        cursorY = (param(0) - 1).clamp(0, height - 1);
        cursorX = (param(1) - 1).clamp(0, width - 1);
      case 'J':
        if ((params.firstOrNull ?? 0) == 2) _clearScreen();
      case 'K':
        _clearLine(params.firstOrNull ?? 0);
      case 'm':
        final effective = params.isEmpty ? const [0] : params;
        if (effective.contains(0)) _sgr = '';
        final remaining = effective.where((value) => value != 0).toList();
        if (remaining.isNotEmpty) {
          _sgr += '\x1b[${remaining.join(';')}m';
        }
      case 'n':
        switch (params.firstOrNull ?? 0) {
          case 5:
            _pendingResponses.write('\x1b[0n');
          case 6:
            final row = cursorY.clamp(0, height - 1) + 1;
            final column = cursorX.clamp(0, width - 1) + 1;
            _pendingResponses.write('\x1b[$row;${column}R');
        }
      case 'c':
        _pendingResponses.write('\x1b[?1;2c');
    }
  }

  List<int> _keyboardParams(String value) {
    if (value.isEmpty) return const [];
    return value.split(';').map((part) => int.tryParse(part) ?? 0).toList();
  }

  void _applyKeyboardFlags(int flags, int mode) {
    final supported = flags & _supportedKeyboardEnhancements;
    keyboardEnhancementFlags = switch (mode) {
      2 => keyboardEnhancementFlags | supported,
      3 => keyboardEnhancementFlags & ~supported,
      _ => supported,
    };
  }

  void _setAlternateScreen(bool enabled) {
    if (enabled == alternateScreen) return;
    if (enabled) {
      _primaryScreen = _SavedScreen(
        rows: _rows,
        cursorX: cursorX,
        cursorY: cursorY,
        sgr: _sgr,
        cursorVisible: cursorVisible,
        scrollOffset: scrollOffset,
        keyboardEnhancementFlags: keyboardEnhancementFlags,
        keyboardFlagStack: List.of(_keyboardFlagStack),
      );
      _rows = List.generate(
        height,
        (_) => List.generate(width, (_) => _Cell()),
      );
      cursorX = 0;
      cursorY = 0;
      _sgr = '';
      cursorVisible = true;
      scrollOffset = 0;
      keyboardEnhancementFlags = 0;
      _keyboardFlagStack.clear();
      alternateScreen = true;
      return;
    }

    final primary = _primaryScreen;
    if (primary != null) {
      _rows = primary.rows;
      cursorX = primary.cursorX;
      cursorY = primary.cursorY;
      _sgr = primary.sgr;
      cursorVisible = primary.cursorVisible;
      scrollOffset = primary.scrollOffset.clamp(0, _scrollback.length);
      keyboardEnhancementFlags = primary.keyboardEnhancementFlags;
      _keyboardFlagStack
        ..clear()
        ..addAll(primary.keyboardFlagStack);
    }
    _primaryScreen = null;
    alternateScreen = false;
  }

  void _clearScreen() {
    for (final row in _rows) {
      for (final cell in row) {
        cell
          ..text = ' '
          ..sgr = '';
      }
    }
  }

  void _clearLine(int mode) {
    final start = mode == 0 ? cursorX : 0;
    final end = mode == 1 ? cursorX + 1 : width;
    for (var x = start; x < end; x++) {
      _rows[cursorY][x]
        ..text = ' '
        ..sgr = '';
    }
  }

  /// Renders the current screen as ANSI-styled text.
  ///
  /// Set [showCursor] when the host terminal cursor is hidden.
  String render({bool showCursor = false}) {
    final out = StringBuffer();
    final visibleRows = alternateScreen
        ? _rows
        : <List<_Cell>>[..._scrollback, ..._rows].sublist(
            (_scrollback.length - scrollOffset).clamp(0, _scrollback.length),
          );
    for (var y = 0; y < height; y++) {
      final row = visibleRows[y];
      var active = '';
      for (var x = 0; x < width; x++) {
        final cell = row[x];
        if (cell.sgr != active) {
          if (active.isNotEmpty) out.write('\x1b[0m');
          if (cell.sgr.isNotEmpty) out.write(cell.sgr);
          active = cell.sgr;
        }
        final isCursor =
            showCursor &&
            scrollOffset == 0 &&
            cursorVisible &&
            y == cursorY &&
            x == cursorX.clamp(0, width - 1);
        if (isCursor) out.write('\x1b[7m');
        out.write(cell.text);
        if (isCursor) {
          out.write('\x1b[27m');
          if (active.isNotEmpty) out.write(active);
        }
      }
      if (active.isNotEmpty) out.write('\x1b[0m');
      if (y + 1 < height) out.write('\n');
    }
    return out.toString();
  }

  void _notify() {
    for (final listener in List.of(_listeners)) {
      listener();
    }
  }
}
