Output pkgs/artisanal_widgets/assets/charting.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1200
Set Height 720
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/widgets/charting.dill"
Enter
Wait+Screen /Charting Widgets/
Sleep 2s
Type "2"
Sleep 900ms
Type "3"
Sleep 900ms
Type "4"
Sleep 900ms
Type "5"
Sleep 900ms
Type "r"
Sleep 900ms
Type "1"
Sleep 900ms
Type "q"
Sleep 1s
