Output pkgs/artisanal_widgets/assets/slider.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1200
Set Height 720
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/widgets/slider.dill"
Enter
Wait+Screen /Volume:/
Sleep 2s
Right
Sleep 500ms
Right
Sleep 500ms
Left
Sleep 500ms
Type "q"
Sleep 1s
