Output pkgs/ultraviolet/assets/effects.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1400
Set Height 800
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/uv/effects.dill"
Enter
Wait+Screen /UV Post Effects/
Sleep 1s
Right
Sleep 1s
Right
Sleep 1s
Type "q"
Sleep 1s
