Output pkgs/ultraviolet/assets/uv_demo.gif

Require dart

Set Shell "bash"
Set FontFamily "DejaVu Sans Mono"
Set FontSize 16
Set LetterSpacing 0
Set Width 1000
Set Height 520
Set Theme "Catppuccin Mocha"
Set TypingSpeed 35ms
Set PlaybackSpeed 1.25
Set CursorBlink false

Type "dart run build/vhs/uv/uv_demo.dill"
Enter
Wait+Screen /Press "q" to quit/
Sleep 1s
Type "m"
Sleep 1s
Type "c"
Sleep 1s
Type "q"
Sleep 1s
