import 'package:driver_tests/src/tests/query_builder/crud_operations_tests.dart';
import 'package:driver_tests/src/tests/query_builder/raw_query_helpers_tests.dart';

import 'query_builder/aggregation_tests.dart';
import 'query_builder/batch_operations_tests.dart';
import 'query_builder/cache_tests.dart';
import 'query_builder/change_tracking_tests.dart';
import 'query_builder/chunking_streaming_tests.dart';
import 'query_builder/conditional_tests.dart';
import 'query_builder/convenience_methods_tests.dart';
import 'query_builder/date_time_tests.dart';
import 'query_builder/driver_extension_tests.dart';
import 'query_builder/fresh_tests.dart';
import 'query_builder/full_text_search_tests.dart';
import 'query_builder/generated_relation_accessors_tests.dart';
import 'query_builder/insert_defaults_tests.dart';
import 'query_builder/join_clauses_tests.dart';
import 'query_builder/json_query_tests.dart';
import 'query_builder/lazy_loading_tests.dart';
import 'query_builder/limit_offset_clauses_tests.dart';
import 'query_builder/model_replication_tests.dart';
import 'query_builder/order_by_clauses_tests.dart';
import 'query_builder/queryrow_sync_tests.dart';
import 'query_builder/refresh_tests.dart';
import 'query_builder/relation_aggregate_tests.dart';
import 'query_builder/relation_mutation_tests.dart';
import 'query_builder/relation_resolver_cache_tests.dart';
import 'query_builder/relations_accessor_tests.dart';
import 'query_builder/scope_tests.dart';
import 'query_builder/select_clauses_tests.dart';
import 'query_builder/subquery_tests.dart';
import 'query_builder/timestamp_tests.dart';
import 'query_builder/typed_predicate_fields_tests.dart';
import 'query_builder/upsert_operations_tests.dart';
import 'query_builder/where_clauses_tests.dart';

void runDriverQueryBuilderTests() {
  runWhereClausesTests();
  runFullTextSearchTests();
  runTypedPredicateFieldsTests();
  runOrderByClausesTests();
  runLimitOffsetClausesTests();
  runSelectClausesTests();
  runAggregationTests();
  runJoinClausesTests();
  runLazyLoadingTests();
  runRelationAggregateTests();
  runRelationMutationTests();
  runRefreshTests();
  runFreshTests();
  runQueryRowSyncTests();
  runRelationsAccessorTests();
  runRelationResolverCacheTests();
  runGeneratedRelationAccessorsTests();
  runCrudOperationsTests();
  runInsertDefaultsTests();
  runUpsertOperationsTests();

  // New tests for missing coverage
  runJsonQueryTests();
  runDateTimeQueryTests();
  runChunkingStreamingTests();
  runScopeTests();
  runConditionalTests();
  runSubqueryTests();
  runRawQueryHelperTests();
  runBatchOperationsTests();
  runCacheTests();
  runModelReplicationTests();
  runChangeTrackingTests();
  runConvenienceMethodsTests();
  runTimestampTests();
  runDriverExtensionTests();
}
