/// Deterministic fuzz helpers for widget tests.
library;

import 'dart:math' as math;

import 'package:artisanal/terminal.dart' as terminal_keys;
import 'package:artisanal/tui.dart' show MouseButton;

import 'widget_tester.dart';

const _defaultFuzzActions = <WidgetFuzzAction>[
  WidgetFuzzAction.key,
  WidgetFuzzAction.specialKey,
  WidgetFuzzAction.paste,
  WidgetFuzzAction.mouseMove,
  WidgetFuzzAction.tap,
  WidgetFuzzAction.drag,
  WidgetFuzzAction.resize,
  WidgetFuzzAction.pump,
];

const _defaultSpecialKeys = <terminal_keys.KeyType>[
  terminal_keys.KeyType.enter,
  terminal_keys.KeyType.tab,
  terminal_keys.KeyType.backspace,
  terminal_keys.KeyType.delete,
  terminal_keys.KeyType.escape,
  terminal_keys.KeyType.up,
  terminal_keys.KeyType.down,
  terminal_keys.KeyType.left,
  terminal_keys.KeyType.right,
  terminal_keys.KeyType.home,
  terminal_keys.KeyType.end,
  terminal_keys.KeyType.pageUp,
  terminal_keys.KeyType.pageDown,
];

const _defaultPasteSamples = <String>[
  'alpha',
  'beta gamma',
  'line one\nline two',
  '[]{}()<>"',
];

/// Scripted action families generated by [WidgetFuzzer].
enum WidgetFuzzAction {
  key,
  specialKey,
  paste,
  mouseMove,
  tap,
  drag,
  resize,
  pump,
}

/// Configuration for a deterministic widget fuzz run.
final class WidgetFuzzOptions {
  /// Creates deterministic fuzz options.
  const WidgetFuzzOptions({
    this.seed = 1,
    this.steps = 100,
    this.actions = _defaultFuzzActions,
    this.keyAlphabet = 'abcdefghijklmnopqrstuvwxyz0123456789+-=[]{};:,./?_ ',
    this.specialKeys = _defaultSpecialKeys,
    this.pasteSamples = _defaultPasteSamples,
    this.minScreenWidth = 20,
    this.maxScreenWidth = 120,
    this.minScreenHeight = 8,
    this.maxScreenHeight = 40,
    this.maxDragSteps = 4,
    this.captureFrames = false,
  }) : assert(steps >= 0),
       assert(keyAlphabet.length > 0),
       assert(minScreenWidth > 0),
       assert(maxScreenWidth >= minScreenWidth),
       assert(minScreenHeight > 0),
       assert(maxScreenHeight >= minScreenHeight),
       assert(maxDragSteps >= 1);

  /// Seed passed to Dart's deterministic [math.Random].
  final int seed;

  /// Number of generated actions to attempt.
  final int steps;

  /// Action families eligible for random selection.
  final List<WidgetFuzzAction> actions;

  /// Characters used when generating rune key input.
  final String keyAlphabet;

  /// Special keys used by [WidgetFuzzAction.specialKey].
  final List<terminal_keys.KeyType> specialKeys;

  /// Paste payload corpus used by [WidgetFuzzAction.paste].
  final List<String> pasteSamples;

  /// Minimum generated terminal width for resize steps.
  final int minScreenWidth;

  /// Maximum generated terminal width for resize steps.
  final int maxScreenWidth;

  /// Minimum generated terminal height for resize steps.
  final int minScreenHeight;

  /// Maximum generated terminal height for resize steps.
  final int maxScreenHeight;

  /// Maximum number of intermediate mouse moves generated for drag steps.
  final int maxDragSteps;

  /// Whether to record frames while fuzzing.
  final bool captureFrames;
}

/// One generated fuzz action.
final class WidgetFuzzStep {
  const WidgetFuzzStep({
    required this.index,
    required this.action,
    this.text,
    this.keyType,
    this.x,
    this.y,
    this.endX,
    this.endY,
    this.width,
    this.height,
    this.dragSteps,
  });

  /// Zero-based action index in the run.
  final int index;

  /// Action family.
  final WidgetFuzzAction action;

  /// Generated text for key and paste actions.
  final String? text;

  /// Generated key type for special-key actions.
  final terminal_keys.KeyType? keyType;

  /// Primary X coordinate for mouse actions.
  final int? x;

  /// Primary Y coordinate for mouse actions.
  final int? y;

  /// Drag destination X coordinate.
  final int? endX;

  /// Drag destination Y coordinate.
  final int? endY;

  /// Generated terminal width for resize actions.
  final int? width;

  /// Generated terminal height for resize actions.
  final int? height;

  /// Number of generated drag motion steps.
  final int? dragSteps;

  @override
  String toString() {
    return switch (action) {
      WidgetFuzzAction.key => '#$index key "$text"',
      WidgetFuzzAction.specialKey => '#$index specialKey ${keyType?.name}',
      WidgetFuzzAction.paste => '#$index paste ${text?.length ?? 0} chars',
      WidgetFuzzAction.mouseMove => '#$index mouseMove $x,$y',
      WidgetFuzzAction.tap => '#$index tap $x,$y',
      WidgetFuzzAction.drag =>
        '#$index drag $x,$y -> $endX,$endY steps=$dragSteps',
      WidgetFuzzAction.resize => '#$index resize ${width}x$height',
      WidgetFuzzAction.pump => '#$index pump',
    };
  }
}

/// Result of a deterministic widget fuzz run.
final class WidgetFuzzResult {
  const WidgetFuzzResult({
    required this.seed,
    required this.requestedSteps,
    required this.history,
    required this.frames,
    this.failedStep,
    this.error,
    this.stackTrace,
  });

  /// Seed used for the run.
  final int seed;

  /// Number of steps requested by [WidgetFuzzOptions.steps].
  final int requestedSteps;

  /// All generated steps, including the failed step when a failure occurs.
  final List<WidgetFuzzStep> history;

  /// Frames recorded during fuzzing when frame capture was enabled.
  final List<WidgetTestFrame> frames;

  /// Step that failed, if any.
  final WidgetFuzzStep? failedStep;

  /// Captured error from the failed step, if any.
  final Object? error;

  /// Captured stack trace from the failed step, if any.
  final StackTrace? stackTrace;

  /// Whether the run completed without an exception.
  bool get passed => error == null;

  /// Number of generated steps that completed.
  int get completedSteps => passed ? history.length : history.length - 1;

  /// Throws [WidgetFuzzFailure] when [passed] is false.
  void throwIfFailed() {
    if (passed) return;
    throw WidgetFuzzFailure(this);
  }
}

/// Exception thrown by [WidgetFuzzResult.throwIfFailed].
final class WidgetFuzzFailure implements Exception {
  /// Creates a failure wrapper for [result].
  const WidgetFuzzFailure(this.result);

  /// Failed fuzz result.
  final WidgetFuzzResult result;

  @override
  String toString() {
    final failed = result.failedStep;
    final tail = result.history.length <= 8
        ? result.history
        : result.history.sublist(result.history.length - 8);
    final history = tail.map((step) => '  $step').join('\n');
    return 'Widget fuzz failed at step $failed '
        '(seed=${result.seed}, completed=${result.completedSteps}/'
        '${result.requestedSteps}): ${result.error}\n'
        'Recent steps:\n$history';
  }
}

/// Deterministic random input harness for [WidgetTester].
final class WidgetFuzzer {
  /// Creates a fuzzer bound to [tester].
  WidgetFuzzer(this.tester, {this.options = const WidgetFuzzOptions()})
    : _random = math.Random(options.seed) {
    _validateOptions(options);
  }

  /// Tester receiving generated events.
  final WidgetTester tester;

  /// Run options.
  final WidgetFuzzOptions options;

  final math.Random _random;

  /// Runs generated input against [tester] and returns a structured result.
  WidgetFuzzResult run() {
    final history = <WidgetFuzzStep>[];
    var frames = const <WidgetTestFrame>[];
    WidgetFuzzStep? failedStep;
    Object? error;
    StackTrace? stackTrace;

    if (options.captureFrames) {
      tester.startFrameRecording(
        clearExisting: true,
        captureCurrentFrame: true,
      );
    }

    try {
      for (var index = 0; index < options.steps; index++) {
        final step = _nextStep(index);
        history.add(step);
        _apply(step);
      }
    } catch (caughtError, caughtStackTrace) {
      failedStep = history.isEmpty ? null : history.last;
      error = caughtError;
      stackTrace = caughtStackTrace;
    } finally {
      if (options.captureFrames) {
        frames = tester.stopFrameRecording();
      }
    }

    return WidgetFuzzResult(
      seed: options.seed,
      requestedSteps: options.steps,
      history: List<WidgetFuzzStep>.unmodifiable(history),
      frames: frames,
      failedStep: failedStep,
      error: error,
      stackTrace: stackTrace,
    );
  }

  WidgetFuzzStep _nextStep(int index) {
    final action = options.actions[_random.nextInt(options.actions.length)];
    return switch (action) {
      WidgetFuzzAction.key => WidgetFuzzStep(
        index: index,
        action: action,
        text: _nextKeyChar(),
      ),
      WidgetFuzzAction.specialKey => WidgetFuzzStep(
        index: index,
        action: action,
        keyType:
            options.specialKeys[_random.nextInt(options.specialKeys.length)],
      ),
      WidgetFuzzAction.paste => WidgetFuzzStep(
        index: index,
        action: action,
        text:
            options.pasteSamples[_random.nextInt(options.pasteSamples.length)],
      ),
      WidgetFuzzAction.mouseMove => WidgetFuzzStep(
        index: index,
        action: action,
        x: _nextX(),
        y: _nextY(),
      ),
      WidgetFuzzAction.tap => WidgetFuzzStep(
        index: index,
        action: action,
        x: _nextX(),
        y: _nextY(),
      ),
      WidgetFuzzAction.drag => WidgetFuzzStep(
        index: index,
        action: action,
        x: _nextX(),
        y: _nextY(),
        endX: _nextX(),
        endY: _nextY(),
        dragSteps: 1 + _random.nextInt(options.maxDragSteps),
      ),
      WidgetFuzzAction.resize => WidgetFuzzStep(
        index: index,
        action: action,
        width: _nextInRange(options.minScreenWidth, options.maxScreenWidth),
        height: _nextInRange(options.minScreenHeight, options.maxScreenHeight),
      ),
      WidgetFuzzAction.pump => WidgetFuzzStep(index: index, action: action),
    };
  }

  void _apply(WidgetFuzzStep step) {
    switch (step.action) {
      case WidgetFuzzAction.key:
        tester.sendKey(step.text!);
      case WidgetFuzzAction.specialKey:
        tester.sendSpecialKey(step.keyType!);
      case WidgetFuzzAction.paste:
        tester.pasteText(step.text!);
      case WidgetFuzzAction.mouseMove:
        tester.mouseMove(step.x!, step.y!);
      case WidgetFuzzAction.tap:
        tester.tapAt(step.x!, step.y!);
      case WidgetFuzzAction.drag:
        tester.drag(
          step.x!,
          step.y!,
          step.endX!,
          step.endY!,
          steps: step.dragSteps!,
          button: MouseButton.left,
        );
      case WidgetFuzzAction.resize:
        tester.resize(step.width!, step.height!);
      case WidgetFuzzAction.pump:
        tester.pump();
    }
  }

  String _nextKeyChar() {
    final index = _random.nextInt(options.keyAlphabet.runes.length);
    return String.fromCharCode(options.keyAlphabet.runes.elementAt(index));
  }

  int _nextX() => _random.nextInt(_positive(tester.screenWidth));

  int _nextY() => _random.nextInt(_positive(tester.screenHeight));

  int _nextInRange(int min, int max) => min + _random.nextInt(max - min + 1);

  static int _positive(int value) => math.max(1, value).toInt();

  static void _validateOptions(WidgetFuzzOptions options) {
    if (options.actions.isEmpty) {
      throw ArgumentError.value(
        options.actions,
        'actions',
        'must not be empty',
      );
    }
    if (options.specialKeys.isEmpty) {
      throw ArgumentError.value(
        options.specialKeys,
        'specialKeys',
        'must not be empty',
      );
    }
    if (options.pasteSamples.isEmpty) {
      throw ArgumentError.value(
        options.pasteSamples,
        'pasteSamples',
        'must not be empty',
      );
    }
  }
}

/// Convenience extension for running deterministic fuzz input.
extension WidgetTesterFuzzing on WidgetTester {
  /// Runs a deterministic fuzz sequence against this tester.
  WidgetFuzzResult fuzz({
    WidgetFuzzOptions options = const WidgetFuzzOptions(),
  }) {
    return WidgetFuzzer(this, options: options).run();
  }
}
