import 'dart:convert';
import 'dart:typed_data';

/// Original synthetic font from ultraviolet/test/support/raster_test_font.dart.
///
/// A local copy keeps capture tests independent of installed fonts and another
/// package's unpublished test files. Glyphs: space, A, O, and 界.
Uint8List testFontBytes() => base64Decode(_font.replaceAll(RegExp(r'\s'), ''));

const _font = '''
AAEAAAAHAEAAAgAwY21hcAAAAAAAAAB8AAAATGdseWYAAAAAAAAAyAAAAHxoZWFkAAAAAAAAAUQAAAA2aGhl
YQAAAAAAAAF8AAAAJGhtdHgAAAAAAAABoAAAABRsb2NhAAAAAAAAAbQAAAAYbWF4cAAAAAAAAAHMAAAAIAAA
AAEAAwAKAAAADAAMAAAAAABAAAAAAAAAAAQAAAAgAAAAIAAAAAEAAABBAAAAQQAAAAIAAABPAAAATwAAAAMA
AHVMAAB1TAAAAAQAAQAAAAAAAAAAAAMAAAEBAQEAZAGQAAD+cAAAAAACvAAAAAIAAAAAAAAAAAADAAcAAAEB
AQEBAQEBAAACWAAA/agAyAAAAMgAAAAAAAACvAAA/gwBLAAA/tQAAQAAAAAAAAAAAAMAAAEBAQEAAASwAAD7
UAAAAAACvAAAAAEAAAAAAAAAAAAAXw889QAAA+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA
AAAAAQAAAyD/OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUCWAAAAlgAAAJYAAACWAAABLAAAAAAAAAA
AAAAAAAAAAAAACIAAABaAAAAfAABAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
''';
